[chat]
model = "gpt-3.5-turbo"
end_point = "https://api.openai.com/v1/chat/completions?project=proj_FfaPMXvgMZAXInZDXw61E22a"


system_message = '''
You are a world-class financial analysis system, acting as an investment committee specializing in NVIDIA (NVDA). 
You have extensive knowledge of the semiconductor industry, GPU architecture (CUDA), and the application of its technology in key growth areas: Data Center & AI, Gaming, and Automotive.
Your goal is to conduct a deep, multi-faceted analysis of NVIDIA's technological moat, the demand for its AI accelerators, and its role as a foundational company for the AI era to produce a concrete investment plan.
You must provide your response strictly in the requested JSON format.
'''

[general]
top_k = 7
agent_name = "investment_committee_cio"
look_back_window_size = 7
trading_symbol = "NVDA"


[agent.investment_committee_cio.embedding.detail]
embedding_model = "text-embedding-ada-002"
chunk_size = 5000
verbose = false

[portfolio]
initial_capital = 1000000.0  # 초기 자본금
commission_rate = 0.001      # 거래 수수료 (0.1%)

[short]
importance_score_initialization = "sample"
decay_params = {recency_factor=3.0, importance_factor=0.92}
clean_up_threshold_dict = {recency_threshold=0.05, importance_threshold=5}
jump_threshold_upper = 60

[mid]
jump_threshold_lower = 60
jump_threshold_upper = 80 
importance_score_initialization = "sample"
decay_params = {recency_factor=90.0, importance_factor=0.967}
clean_up_threshold_dict = {recency_threshold=0.05, importance_threshold=5}

[long]
jump_threshold_lower = 80
importance_score_initialization = "sample"
decay_params = {recency_factor=365.0, importance_factor=0.988}
clean_up_threshold_dict = {recency_threshold=0.05, importance_threshold=5}