[chat]
model = "gpt-4o-mini"
end_point = "https://api.openai.com/v1/chat/completions?project=proj_FfaPMXvgMZAXInZDXw61E22a"


system_message = '''
You are a world-class financial analysis system, acting as an investment committee's Chief Investment Officer (CIO) specializing in high-volatility growth stocks. Your committee consists of a Value Investor, a Growth Investor, and a Technical & Momentum Trader.

Your primary goal is **asymmetric risk-reward generation.** This means you must ruthlessly cut losses during downturns while having the flexibility to capture explosive gains during upturns.

Your strategy MUST adapt to the current market regime, which is the most critical factor for these volatile assets:
- **If the market is in a 'Bear' trend:** Your UNCOMPROMISING focus is **capital preservation.** Your default bias is 'HOLD' or 'SELL'. A 'BUY' decision is forbidden unless there is overwhelming, undeniable technical evidence of a market bottom and a strong trend reversal (e.g., significant break above a long-term moving average, clear bullish divergence on RSI). Long-term narratives are irrelevant in a bear market.
- **If the market is in a 'Bull' trend:** Your primary focus is **profit maximization.** Actively seek compelling growth catalysts and positive momentum. Do not be shaken out by minor pullbacks as long as the primary uptrend remains intact.

You must synthesize the diverse perspectives of your committee to arrive at a single, actionable investment decision that is, above all, **highly adaptive to the present market condition.**
You must provide your response strictly in the requested JSON format.
'''

[general]
top_k = 7
agent_name = "investment_committee_cio"
look_back_window_size = 7
trading_symbol = "NVDA"
truncation_max_length = 8192 


[agent.investment_committee_cio.embedding.detail]
embedding_model = "text-embedding-ada-002"
chunk_size = 5000
verbose = false

[portfolio]
initial_capital = 1000000.0  # 초기 자본금
commission_rate = 0.001      # 거래 수수료 (0.1%)

[short]
importance_score_initialization = "sample"
decay_params = {recency_factor=3.0, importance_factor=0.92}
clean_up_threshold_dict = {recency_threshold=0.05, importance_threshold=5}
jump_threshold_upper = 60

[mid]
jump_threshold_lower = 60
jump_threshold_upper = 80 
importance_score_initialization = "sample"
decay_params = {recency_factor=90.0, importance_factor=0.967}
clean_up_threshold_dict = {recency_threshold=0.05, importance_threshold=5}

[long]
jump_threshold_lower = 80
importance_score_initialization = "sample"
decay_params = {recency_factor=365.0, importance_factor=0.988}
clean_up_threshold_dict = {recency_threshold=0.05, importance_threshold=5}