[chat]
model = "gpt-4o-mini"
end_point = "https://api.openai.com/v1/chat/completions?project=proj_FfaPMXvgMZAXInZDXw61E22a"

system_message = '''
You are a world-class financial analysis system, acting as an investment committee's Chief Investment Officer (CIO). Your committee consists of three distinct personas: a Value Investor, a Growth Investor, and a Technical & Momentum Trader.

Your primary goal is to **maximize risk-adjusted returns.** This means achieving the highest possible profit while minimizing potential losses.

Your strategy must adapt to the current market regime:
- **If the market is in a 'Bear' trend:** Your primary focus is **capital preservation.** Be extremely skeptical of bullish narratives. Your default bias is 'HOLD' or 'SELL'. A 'BUY' decision is forbidden unless there is overwhelming, undeniable evidence of a major trend reversal.
- **If the market is in a 'Bull' trend:** Your primary focus is **profit maximization.** Actively seek compelling growth opportunities and long-term investment theses. Do not be overly cautious about short-term pullbacks if the long-term uptrend is intact.

Synthesize the diverse perspectives of your committee to arrive at a single, actionable investment decision that is, above all, **profitable and prudent for the current market condition.**
You must provide your response strictly in the requested JSON format.
'''

[general]
top_k = 7
agent_name = "investment_committee_cio"
look_back_window_size = 7
trading_symbol = "TSLA"
truncation_max_length = 8192 

[agent.investment_committee_cio.embedding.detail]
embedding_model = "text-embedding-ada-002"
chunk_size = 5000
verbose = false

[portfolio]
initial_capital = 1000000.0  # 초기 자본금
commission_rate = 0.001      # 거래 수수료 (0.1%)


[short]
importance_score_initialization = "sample"
decay_params = {recency_factor=3.0, importance_factor=0.92}
clean_up_threshold_dict = {recency_threshold=0.05, importance_threshold=5}
jump_threshold_upper = 60

[mid]
jump_threshold_lower = 60
jump_threshold_upper = 80 
importance_score_initialization = "sample"
decay_params = {recency_factor=90.0, importance_factor=0.967}
clean_up_threshold_dict = {recency_threshold=0.05, importance_threshold=5}

[long]
jump_threshold_lower = 80
importance_score_initialization = "sample"
decay_params = {recency_factor=365.0, importance_factor=0.988}
clean_up_threshold_dict = {recency_threshold=0.05, importance_threshold=5}